/**
 * The routes a sign-in is allowed to hand the athlete back to.
 *
 * `next` arrives as a query parameter, which makes it attacker-controlled: a link to
 * `/auth?next=evil://...` is a redirect this app did not intend, and on a native target some
 * values are handled by the OS rather than by Expo Router. So the value is checked against what
 * this app actually has, and anything else falls back to the feed.
 *
 * The check is an allowlist rather than a "starts with a slash" test, because a prefix test is
 * enough to authorise `/auth/sign-up`, a screen the athlete was not trying to reach, and enough to
 * be walked one segment at a time to reach anything added later without this file being updated.
 */
const RETURN_ROUTES: ReadonlySet<string> = new Set([
  '/',
  '/add',
  '/favorites',
  '/profile',
  '/settings',
]);

/** A spot id is a uuid, as generated by Postgres. Checked rather than trusted so a path is a spot and not a route. */
const SPOT_PATH = /^\/spot\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Whether a `next` parameter names a screen this app can return to. */
export function isKnownRoute(path: string): boolean {
  return RETURN_ROUTES.has(path) || SPOT_PATH.test(path);
}
